export const sampleTasks = [
  {
    id: 'T-1001',
    objective: 'Design dashboard layout for Apollo',
    project: 'Apollo',
    subProject: 'Web Revamp',
    assignedBy: 'Ava Cole',
    assignedTo: 'Liam Patel',
    assignedDate: '2025-11-01',
    deadline: '2025-11-12',
    parentTask: 'UX Epic #3',
    skill: 'UX',
    role: 'Designer',
    taskProfile: 'Dashboard',
    taskType: 'Design',
    workingDate: '2025-11-02',
    ai: 'No',
    priority: 'High',
    estimatedTime: '12h',
    startTime: '10:00',
    endTime: '18:00',
    timeTaken: '7h',
    status: 'In Progress',
    reportLink: 'https://docs.example.com/apollo-dashboard',
    reviewStatus: 'Pending',
    completion: 42,
    resourceUtilised: 'Figma, FigJam',
    feedbackImplemented: false,
    startDate: '2025-11-01',
    submittedDate: '',
    reviewedDate: '',
    reviewedBy: '',
    reviewNotes: '',
    skillsAchieved: 'Wireframing',
  },
  {
    id: 'T-1002',
    objective: 'Backend APIs for time tracking',
    project: 'Hermes',
    subProject: 'Timesheets',
    assignedBy: 'Noah Reyes',
    assignedTo: 'Sophia Kim',
    assignedDate: '2025-11-03',
    deadline: '2025-11-20',
    parentTask: 'API Epic #5',
    skill: 'Node',
    role: 'Backend',
    taskProfile: 'API',
    taskType: 'Development',
    workingDate: '2025-11-03',
    ai: 'Yes',
    priority: 'Medium',
    estimatedTime: '20h',
    startTime: '09:00',
    endTime: '17:30',
    timeTaken: '6h',
    status: 'To Do',
    reportLink: '',
    reviewStatus: 'Not Started',
    completion: 10,
    resourceUtilised: 'FastAPI, MongoDB',
    feedbackImplemented: false,
    startDate: '2025-11-03',
    submittedDate: '',
    reviewedDate: '',
    reviewedBy: '',
    reviewNotes: '',
    skillsAchieved: 'Auth, DB Models',
  },
  {
    id: 'T-1003',
    objective: 'QA test cases for payments',
    project: 'Zephyr',
    subProject: 'Billing',
    assignedBy: 'Emma Stone',
    assignedTo: 'Olivia Park',
    assignedDate: '2025-10-28',
    deadline: '2025-11-05',
    parentTask: 'QA Epic #2',
    skill: 'QA',
    role: 'QA Engineer',
    taskProfile: 'Testing',
    taskType: 'QA',
    workingDate: '2025-10-30',
    ai: 'No',
    priority: 'Low',
    estimatedTime: '8h',
    startTime: '11:00',
    endTime: '17:00',
    timeTaken: '5h',
    status: 'Under Review',
    reportLink: 'https://docs.example.com/zephyr-qa',
    reviewStatus: 'In Review',
    completion: 85,
    resourceUtilised: 'Jest, Cypress',
    feedbackImplemented: true,
    startDate: '2025-10-28',
    submittedDate: '2025-11-04',
    reviewedDate: '2025-11-06',
    reviewedBy: 'QA Lead',
    reviewNotes: 'Minor fixes',
    skillsAchieved: 'E2E Testing',
  },
  {
    id: 'T-1004',
    objective: 'Roll out onboarding email sequence',
    project: 'Apollo',
    subProject: 'Growth',
    assignedBy: 'Mia Chen',
    assignedTo: 'Ethan Wright',
    assignedDate: '2025-10-21',
    deadline: '2025-10-30',
    parentTask: 'Growth Epic #1',
    skill: 'Marketing',
    role: 'Marketer',
    taskProfile: 'Lifecycle',
    taskType: 'Campaign',
    workingDate: '2025-10-22',
    ai: 'Yes',
    priority: 'High',
    estimatedTime: '10h',
    startTime: '10:00',
    endTime: '16:30',
    timeTaken: '9h',
    status: 'Completed',
    reportLink: 'https://docs.example.com/onboarding',
    reviewStatus: 'Approved',
    completion: 100,
    resourceUtilised: 'Customer.io',
    feedbackImplemented: true,
    startDate: '2025-10-21',
    submittedDate: '2025-10-29',
    reviewedDate: '2025-10-30',
    reviewedBy: 'Growth Lead',
    reviewNotes: 'Great work',
    skillsAchieved: 'Automation',
  },
];
